version: '3'
services:
    haproxy:
        build: loadbal
        ports:
            - 1936:1936
            - 80:80
        depends_on:
            - cachea
            - cacheb
    cachea:
        build: cache
        environment:
            SSL_HOSTNAME: cachea
        links:
            - "proxya:web"
        depends_on:
            - ca
            - proxya
    cacheb:
        build: cache
        environment:
            SSL_HOSTNAME: cacheb
        links:
            - "proxyb:web"
        depends_on:
            - ca
            - proxyb
    proxya:
        build: proxy
        environment:
            SSL_HOSTNAME: proxya
        depends_on:
            - pweb
    proxyb:
        build: proxy
        environment:
            SSL_HOSTNAME: proxyb 
        depends_on:
            - pweb
    pweb:
        build: web
    db:
        build: mysql
        restart: always
        environment:
            MYSQL_DATABASE: skitter
            MYSQL_USER: skitter_overlord
            MYSQL_PASSWORD: a_GENerIC_p@ssW0rd
            MYSQL_ROOT_PASSWORD: "included because docker said so"
    authentication:
        build: auth
        ports:
            - 8080:8080
        depends_on:
            - db
            - ca
        command: dockerize -wait http://db:3306 -wait http://ca:8888
    ca:
        build: app_ca
