version: '3'
services:
    haproxy:
        build: loadbal
        ports:
            - 1936:1936
            - 80:80
        depends_on:
            - cachea
            - cacheb
    cachea:
        build: cache
        links:
            - "weba:web"
        depends_on:
            - weba
    cacheb:
        build: cache
        links:
            - "webb:web"
        depends_on:
            - webb
    weba:
        build: web
    webb:
        build: web
    # Activity 7
    skitdb:
        build: elasticsearch
    skitcreate:
        build: skit-create
        ports:
            - 81:81
        depends_on: 
            - skitdb
            - ca
        command: dockerize -wait http://skitdb:9200 -wait http://ca:8888
    # Activity 4
    db:
        build: mysql
        restart: always
        environment:
            MYSQL_DATABASE: skitter
            MYSQL_USER: skitter_overlord
            MYSQL_PASSWORD: a_GENerIC_p@ssW0rd
            MYSQL_ROOT_PASSWORD: "included because docker said so"
    authentication:
        build: auth
        ports:
            - 8080:8080
        depends_on:
            - db
            - ca
        command: dockerize -wait http://db:3306 -wait http://ca:8888
    ca:
        build: app_ca
